// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Kjir0MkOUoTaylsJVdMXwm9Wa1KS5PQ',
    appId: '1:878703419944:web:7cc8d39748b25042890b1d',
    messagingSenderId: '878703419944',
    projectId: 'hobbee-a06c0',
    authDomain: 'hobbee-a06c0.firebaseapp.com',
    storageBucket: 'hobbee-a06c0.firebasestorage.app',
    measurementId: 'G-233N3KKN6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD8hmrJRrA23b9VeXAmw-DpuwA3MQ6dew',
    appId: '1:878703419944:android:efc377123980bb9e890b1d',
    messagingSenderId: '878703419944',
    projectId: 'hobbee-a06c0',
    storageBucket: 'hobbee-a06c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-A-TcjWVjkLMgdeqJA_se8rBX9OER3ss',
    appId: '1:878703419944:ios:3fff754d04193916890b1d',
    messagingSenderId: '878703419944',
    projectId: 'hobbee-a06c0',
    storageBucket: 'hobbee-a06c0.firebasestorage.app',
    iosBundleId: 'com.example.hobbeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-A-TcjWVjkLMgdeqJA_se8rBX9OER3ss',
    appId: '1:878703419944:ios:3fff754d04193916890b1d',
    messagingSenderId: '878703419944',
    projectId: 'hobbee-a06c0',
    storageBucket: 'hobbee-a06c0.firebasestorage.app',
    iosBundleId: 'com.example.hobbeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Kjir0MkOUoTaylsJVdMXwm9Wa1KS5PQ',
    appId: '1:878703419944:web:9c565a73178310e4890b1d',
    messagingSenderId: '878703419944',
    projectId: 'hobbee-a06c0',
    authDomain: 'hobbee-a06c0.firebaseapp.com',
    storageBucket: 'hobbee-a06c0.firebasestorage.app',
    measurementId: 'G-BHY3Y4L91B',
  );
}
